name: Deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 20

permissions:
  contents: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: |
          echo "Deployment workflow triggered!"
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   with:
      #     persist-credentials: false

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "${{ env.NODE }}"
      #     cache: npm

      # - name: Install npm dependencies
      #   run: npm ci

      # # - name: Deploy
      # #   run: npm run deploy

      # # - name: Release
      # #   uses: semantic-release/semantic-release@v17
      # #   env:
      # #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
