name: Issue needs example

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  issue-labeled:
    permissions:
      # allow actions-cool/issues-helper to update issues and PRs
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository == 'Yuba-Technology/WorkflowX'
    steps:
      - name: awaiting reply
        if: github.event.label.name == 'needs example'
        uses: actions-cool/issues-helper@a610082f8ac0cf03e357eb8dd0d5e2ba075e017e # v3.6.0
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Bug reports must include a **live demo** of the issue. You can visit our [CONTRIBUTING.md](https://github.com/Yuba-Technology/WorkflowX/blob/main/.github/CONTRIBUTING.md) for more information on how to create a live demo.
