name: Prepare Release

on:
  # push:
  #   branches:
  #     - main
  #     - develop
  # pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 20

permissions:
  contents: write
  pull-requests: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: npx semantic-release
        id: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push and open Pull request
        if: steps.semantic-release.outputs.next_version != ''
        run: |
          git checkout -b release/${{ steps.semantic-release.outputs.next_version  }}
          git add package.json CHANGELOG.md
          git commit -m "chore(release): ${{ steps.semantic-release.outputs.next_version  }}"
          git push origin release/${{ steps.semantic-release.outputs.next_version  }}
          gh pr create --title "chore(release): ${{ steps.semantic-release.outputs.next_version  }}" --body "chore(release): ${{ steps.semantic-release.outputs.next_version  }}" --base main --head release/${{ steps.semantic-release.outputs.next_version  }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
